# Le indica a Prometheus que scrapee el /metrics de nuestra app.
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: pf-cloud-api
  namespace: monitoring
  labels:
    release: monitoreo
spec:
  namespaceSelector:
    matchNames: [pf-app]
  selector:
    matchLabels:
      app.kubernetes.io/name: pf-cloud-api
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
