apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pf-app

resources:
- 00-namespace.yaml
- 10-deployment.yaml
- 20-service.yaml
- 30-ingress.yaml
- 40-hpa.yaml
- 50-pdb.yaml
- 60-networkpolicy.yaml

# El pipeline sobreescribe el tag con: kustomize edit set image ...
images:
- name: ghcr.io/franciscorhaiel/pf-cloud-api
  newName: pf-cloud-api
  newTag: 1.0.0

commonLabels:
  app.kubernetes.io/part-of: pf-cloud
